<!DOCTYPE html>

<html lang="de">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>TimeTrack</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="static/css/style.css" rel="stylesheet" type="text/css">		
	<link href="static/css/bootstrap.min.css" rel="stylesheet" type="text/css">		
	<link href="static/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css">		
	<link href="static/css/newstyle.css" rel="stylesheet" type="text/css">		

	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Josefin+Sans|Nobile">

	<link rel="apple-touch-icon" href="static/img/favicon.png">
	<link rel="shortcut icon" href="static/img/favicon.ico" />
	<link rel="icon" href="static/img/favicon.ico" type="image/ico" />
</head>
<body>
